### ISSUE TITLE
pyxis-elm has a weak namespace

### ISSUE THREAD

**Issue by kioan000** [primait/pyxis#123]
Pyxis for elm library has actually a very weak namespace exposing directly its modules as "Commons" and "Components"

<img width="430" alt="image" src="https://user-images.githubusercontent.com/9343574/159961597-cfe39606-ef5b-421b-9bbd-00d6d0d4d9ad.png">

If in pyxis environment this is enough in the outer world it's not.

It would be much better have a strong and consistent namespace that indicates both the project **and** the version. This would make the usage clearer and should avoid conflicts with other pyxis installations.
eg. Prima.PyxisV4 or PyxisV4

Furthermore the public part of a library name space should avoid "project domain" structural knowledge and it should always refers to a "parent" module. Since we don't have a Commons.elm or a Components.elm related type it may be confusing for a consumer

**Comment by emanuelemacri** [comment]
Resolved in #159
