### ISSUE TITLE
[pyxis-css] "link" class miss cursor:pointer

### ISSUE THREAD

**Issue by kioan000** [primait/pyxis#162]
Since `link` class could be used also on non `<a>` elements  it would be nice to have a `cursor: pointer` property on it.

In SPA where every anchor is automatically handled by the router and pass through browser events even an <a> without href would trigger native reload events.

In case your whole logic is based on a custom "onClick" event that do all internally it's better to use a `<button class="link"> ` but since link doesn't have the property you have a link that doesn't look clickable 

In the following example we have a download link that must be handled via a custom click event by elm (to make a file download with save as)
![image](https://user-images.githubusercontent.com/9343574/168078598-1e99e75c-6030-4285-be65-8f25f9c554d7.png)

**Comment by emanuelemacri** [comment]
Resolved in #168
