### ISSUE TITLE
Form component should be aware of submit and error showing strategies 

### ISSUE THREAD

**Issue by alessiosantangelo** [primait/pyxis#80]
At the moment the `Form` component only keeps aligned items in a particular grid system.

We should let the `Form` know about error showing strategies between: 
- _real time_, a strategy in which errors are shown immediately during user input but when the field is focused
- _on submit_

The Form should also enforce it's api in order to be consistent with design requirements and limitations.

**Comment by ascandone** [comment]
Isn't the "blur" strategy needed too? At least for inputs?  (show the error when the user blurs the input)
